name: lomopl.us
favicon: null
layout_spectrum: 0.20147905475459993
typography_spectrum: 0.6664937604218721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8032342193182558
  lightness: 0.4734221682883799
  saturation: 0.012810526648536325
  rhythmicContrast: 0.06523122312501073
purpose: []
